name: Pytest

on:
  push:
    branshes: [ "dev" ]
  pull_request:
    branshes: [ "dev" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/setup.py'

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Unit Tests
        run:
          python -m pytest -m unit